version: '3'

services: 
  mysql:
    #image: myql-db
    build:
      context: ./Database
      dockerfile: Dockerfile
    ports:
      - 3000:3306
    environment:
      - MYSQL_ROOT_PASSWORD=omar1234 
    restart: always
    volumes:
      - mysqldb:/var/lib/mysql
  
  frontend:
    #image: frontend:latest
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - 4173:4173
    restart: always

  backend:
   # image: backend:final
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    restart: always
    depends_on: 
      - mysql
    
volumes:
  mysqldb: