FROM jenkins/jenkins:latest
#ARG path

USER root

RUN apt-get update && \
 apt-get -qy full-upgrade && \
 apt-get install -y -qy curl && \
 curl https://get.docker.com/ > dockerinstall && \
 chmod 777 dockerinstall && \
 ./dockerinstall 

USER jenkins


#CMD ["/bin/sh", "-c", "chmod 666 /var/run/docker.sock && su jenkins -c '/usr/bin/tini -- /usr/local/bin/jenkins.sh'"]

#CMD ["/bin/sh", "-c", "chmod 666 /var/run/docker.sock && /usr/bin/tini -- /usr/local/bin/jenkins.sh"]
