FROM jenkins/jenkins:latest
#ARG path

USER root

RUN apt-get update && \
 apt-get -qy full-upgrade && \
 apt-get install -y -qy curl && \
 curl https://get.docker.com/ > dockerinstall && \
 chmod 777 dockerinstall && \
 ./dockerinstall 

RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && \
    chmod +x ./kubectl && \
    mv ./kubectl /usr/local/bin/kubectl

RUN apt-get install -y iputils-ping && rm -rf /var/lib/apt/lists/*


RUN touch /var/run/docker.sock
RUN chmod 666 /var/run/docker.sock

USER jenkins



#CMD ["/bin/sh", "-c", "chmod 666 /var/run/docker.sock && su jenkins -c '/usr/bin/tini -- /usr/local/bin/jenkins.sh'"]

#CMD ["/bin/sh", "-c", "chmod 666 /var/run/docker.sock && /usr/bin/tini -- /usr/local/bin/jenkins.sh"]
