def gv

pipeline {
    agent any
    stages {
    
        stage('Setup Environment') {
            steps {
                script {
                    gv = load "${WORKSPACE}/Jenkins/script.groovy" 
                    
                    env.FRONTEND_IMAGE = "omartarekabdelall/todo-list-app:frontend-${env.BUILD_NUMBER}"
                    env.BACKEND_IMAGE = "omartarekabdelall/todo-list-app:backend-${env.BUILD_NUMBER}"
                    env.DATABASE_IMAGE = "omartarekabdelall/todo-list-app:database-${env.BUILD_NUMBER}"
                }
            }
         }

        stage('Build Images') {
            steps {
                script{
                    gv.buildImage()  
                }
            }
        }

        stage('Push Images')
        {
            steps {
                script{
                    gv.pushImage() 
                }
            }
        }

         stage('Update K8s Manifests')
        {
            steps {
                script{

                    sh "sed -i 's|$BACKEND_IMAGE|${BACKEND_IMAGE}|g' k8s/backend-deployment.yaml"
                    sh"cat k8s/backend-deployment.yaml"

                   //sh "envsubst < k8s/frontend-deployment.yaml  frontend-output.yaml"
                    //sh "mv frontend-output.yaml k8s/frontend-deployment.yaml"
           
                }
            }
        }   

        
    }
}
